### ISSUE TITLE
"You must select an SSL version to use." + README mentions stable

### ISSUE THREAD

**Issue by diegoeche** [ponylang/net_ssl#39]
Good day!

I started playing with PonyLang (btw, Great PL design choices, pretty much in love of the language!)

Got the basics from the tutorial, and wanted to do a simple backend for a game I'm working on. Started hacking around a simple HttpServer (with the http_server library) and compiling I got this error:

```
/Personal/PonyTutorial/hellohttp/_corral/github_com_ponylang_net_ssl/net_ssl/x509.pony:72:9: compile error: You must select an SSL version to use.
        compile_error "You must select an SSL version to use."
```

I'm in OSX and installed libressl. I noticed the README provides a command to select the libssl version but it uses `stable` that is not supported anymore. Is there an updated command to pass the `-D` flag within Corral?

I tried googling around, but no success.

**Comment by EpicEric** [comment]
Hi there.

The command should be `corral run -- ponyc -Dopenssl_1.1.x`. Same as the command to compile `http`, with the SSL flag added at the end.
