### ISSUE TITLE
LibreSSL path is wrong for arm macOS

### ISSUE THREAD

**Issue by ergl** [ponylang/net_ssl#51]
We're currently setting the path for LibreSSL to `/usr/local/opt/libressl/lib` on macOS, which is  where homebrew defaulted to installing packages on Intel chips.

On the M1 (and for macOS on arm64 in general), homebrew will install packages under `/opt/homebrew`, so the correct path for those systems should now be `/opt/homebrew/opt/libressl/lib`.

Now that `homebrew` is explicitly in the path, this raises another issue. To my knowledge, the path that we're using now doesn't work if someone installs libressl using macports (that installs to `/opt/local/`), so we're already assuming that libressl was installed using Homebrew.

I'm not sure if defaulting to any of the package managers is a good idea. Perhaps we should remove that line, and tell users to use the `--path` option when using `net_ssl` on macOS?

**Comment by ergl** [comment]
@SeanTAllen I'm worried about dependencies though.

Wouldn't every package that depended on `net_ssl` and used the current `corral run -- ponyc` build approach need to let users know about using `--path`?

Would the same need to happen for every package that, indirectly, depended on `net_ssl`?

**Comment by ergl** [comment]
@SeanTAllen What do you think of going the other way and adding the path for both homebrew and macports on macOS? The pony compiler is already looking in standard places in Linux, so it may make sense to try and do the same on macOS

**Comment by SeanTAllen** [comment]
I'm iffy on it but I'd say, lets do it for now and figure out what our best long term option should be (which I think is "path")

**Comment by ergl** [comment]
@SeanTAllen It seems that macports is already covered by including `/opt/local/lib`, so we would only need to include the path for homebrew under apple silicon
